memodir = "~/.config/memo/_posts"
editor = "nvim"
column = 20
width = 0
selectcmd = "fzf --reverse"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
memotemplate = "~/.config/memo/template.txt"
assetsdir = "."
pluginsdir = "~/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
