memodir = "/Users/j.watanabe/.config/memo/_posts"
editor = "vim"
column = 20
width = 0
selectcmd = "fzf --reverse"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
memotemplate = "~/config/memo/template.txt"
assetsdir = "."
pluginsdir = "/Users/j.watanabe/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
