[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = 'call coc#util#install()'

[[plugins]]
repo = 'nathom/filetype.nvim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'mattn/vim-sonictemplate'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'terryma/vim-expand-region'
