[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
depends = ['fern-preview.vim', 'fern-renderer-nerdfont.vim', 'glyph-palette.vim']

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = 0
# hook_source = 'call coc#util#install()'

[[plugins]]
repo = 'nathom/filetype.nvim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0

[[plugins]]
repo = 'mattn/vim-sonictemplate'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'rebelot/kanagawa.nvim'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'

[[plugins]]
repo = 'akinsho/bufferline.nvim'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'

[[plugins]]
repo = 'phaazon/hop.nvim'

[[plugins]]
repo = 'xiyaowong/nvim-transparent'
