[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'VimEnter'
hook_source = '''lua require('plugins.nvim-lsp')'''

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'folke/lsp-colors.nvim'

[[plugins]]
repo = 'tami5/lspsaga.nvim'
on_source = ['nvim-lspconfig', 'nvim-cmp']
hook_source = '''
lua require('lspsaga').setup()
'''

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = ['nvim-lspconfig', 'nvim-cmp']

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp-signature-help'
on_source = ['nvim-lspconfig', 'nvim-cmp']

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = ['nvim-lspconfig', 'nvim-cmp']

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = ['nvim-lspconfig', 'nvim-cmp']

[[plugins]]
repo = 'hrsh7th/cmp-emoji'
on_source = ['nvim-lspconfig', 'nvim-cmp']

[[plugins]]
repo = 'hrsh7th/cmp-calc'
on_source = ['nvim-lspconfig', 'nvim-cmp']

[[plugins]]
repo = 'f3fora/cmp-spell'
on_source = ['nvim-lspconfig', 'nvim-cmp']

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
on_source = ['nvim-lspconfig', 'nvim-cmp']

[[plugins]]
repo = 'ray-x/cmp-treesitter'
on_source = ['nvim-lspconfig', 'nvim-cmp']

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'onsails/lspkind-nvim'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_source = 'nvim-lspconfig'
hook_source = '''
lua require('nvim-autopairs').setup{}
'''

[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
on_source = 'nvim-lspconfig'
hook_source = ''' lua require('plugins.null-ls').setup() '''
