# 見た目
# 背景透過
[[plugins]]
repo = 'xiyaowong/nvim-transparent'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'nathom/filetype.nvim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0

[[plugins]]
repo = 'rebelot/kanagawa.nvim'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'

[[plugins]]
repo = 'akinsho/bufferline.nvim'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'terryma/vim-expand-region'
