# 依存
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_source = ['todo-comments.nvim', 'telescope.nvim']

# その他
[[plugins]]
repo = 'lambdalisue/fern.vim'
depends = ['fern-preview.vim', 'fern-renderer-nerdfont.vim', 'glyph-palette.vim']

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'

[[plugins]]
repo = 'mattn/vim-sonictemplate'

[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'
on_event = 'VimEnter'

[[plugins]]
repo = 'mattn/vim-maketable'
on_cmd = ['MakeTable']

[[plugins]]
repo = 'andymass/vim-matchup'
on_event = 'VimEnter'

[[plugins]]
repo = 'machakann/vim-sandwich'
on_event = 'VimEnter'

[[plugins]]
repo = 'tpope/vim-repeat'
on_event = 'VimEnter'

[[plugins]]
repo = 'rhysd/clever-f.vim'
on_event = 'VimEnter'

[[plugins]]
repo = 'tpope/vim-commentary'
on_event = 'VimEnter'

[[plugins]]
repo = 'phaazon/hop.nvim'
hook_source = '''lua require("hop").setup()'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
on_source = ['trouble.nvim', 'wilder.nvim', 'alpha-nvim', 'telescope.nvim']

[[plugins]]
repo = 'folke/trouble.nvim'

[[plugins]]
repo = 'segeljakt/vim-silicon'
on_cmd = ['Silicon', 'SiliconHighlight']
hook_source = '''lua require('plugins.silicon')'''

[[plugins]]
repo = 'gelguy/wilder.nvim'
on_event = 'VimEnter'
hook_source = '''lua require('plugins.wilder')'''

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
on_event = 'VimEnter'
hook_source = '''lua require('plugins.indent-blankline')'''

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
on_ft = ['html', 'vue']

[[plugins]]
repo = 'goolord/alpha-nvim'
on_event = 'VimEnter'
hook_source = '''
lua require'alpha'.setup(require'alpha.themes.startify'.config)
'''

[[plugins]]
repo = 'folke/todo-comments.nvim'
on_event = 'VimEnter'
hook_source = '''
lua require('todo-comments').setup({})
'''

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_source = '''
lua require('telescope').setup({defaults={layout_strategy='horizontal', sorting_strategy = 'ascending', layout_config={prompt_position='top'}}})
lua require('telescope').load_extension('fzf')
'''

[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
on_source = ['telescope.nvim']
build = 'make'
