return {
  -- {
  --   'krivahtoo/silicon.nvim',
  --   build = './install.sh',
  --   config = function()
  --     require('silicon').setup({
  --       theme = 'Dracula',
  --       font = "Ricty Discord for Powerline",
  --       background = "#AAAAFF",
  --       line_number = true,
  --       line_pad = 2,
  --       pad_vert = 80,
  --       pad_horiz = 100,
  --       output = {
  --         path = "/home/Desktop/silicon-{time:%Y-%m-%d-%H%M%S}.png",
  --       },
  --       watermark = {
  --         text = ' @nananaman',
  --       },
  --       window_title = function()
  --         return vim.fn.fnamemodify(vim.fn.bufname(vim.fn.bufnr()), ':~:.')
  --       end,
  --     })
  --   end
  -- }
}
