{
  lib,
  config,
  dotfilesDir,
  helpers,
  ...
}:
let
  inherit (config.home) homeDirectory;
  inherit (config.xdg) configHome;
in
{
  home.activation.linkDotfiles = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    ${helpers.activation.mkLinkForce}

    # Neovim
    link_force "${dotfilesDir}/nvim" "${configHome}/nvim"

    # Zsh
    link_force "${dotfilesDir}/zsh/zshrc" "${homeDirectory}/.zshrc"
    link_force "${dotfilesDir}/zsh/sheldon" "${configHome}/sheldon"

    # Ghostty
    link_force "${dotfilesDir}/ghostty" "${configHome}/ghostty"
    $DRY_RUN_CMD mkdir -p "${homeDirectory}/Library/Application Support/com.mitchellh.ghostty"
    link_force "${dotfilesDir}/ghostty/config" "${homeDirectory}/Library/Application Support/com.mitchellh.ghostty/config"

    # AeroSpace
    link_force "${dotfilesDir}/aerospace/aerospace.toml" "${homeDirectory}/.aerospace.toml"

    # Lazygit
    link_force "${dotfilesDir}/lazygit" "${configHome}/lazygit"

    # cspell
    link_force "${dotfilesDir}/cspell" "${configHome}/cspell"

    # sql-formatter
    link_force "${dotfilesDir}/sql-formatter" "${configHome}/sql-formatter"

    # Git (global ignore only — config is generated by home-manager)
    $DRY_RUN_CMD mkdir -p "${configHome}/git"
    link_force "${dotfilesDir}/git/ignore" "${configHome}/git/ignore"

    # stylua
    link_force "${dotfilesDir}/stylua.toml" "${configHome}/stylua.toml"

    # sandbox-exec (template substitution)
    $DRY_RUN_CMD mkdir -p "${configHome}/sandbox-exec"
    sed "s|@HOME@|${homeDirectory}|g" \
      "${dotfilesDir}/sandbox-exec/agent.sb.in" \
      > "${configHome}/sandbox-exec/agent.sb"
  '';
}
