set -g prefix C-g
unbind C-b
bind C-g send-prefix

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g history-limit 50000
set -g escape-time 10
set -g focus-events on
set -g extended-keys on
set -g extended-keys-format csi-u

set -g set-clipboard on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB,tmux-256color:RGB,xterm-ghostty:RGB"

source-file ~/.config/tmux/style.tmux

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind f display-popup -E -w 80% -h 80% "zsh -ic tmux-ghq-session"
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"
