[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'reireias/vim-cheatsheet'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'easymotion/vim-easymotion'
