[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'reireias/vim-cheatsheet'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
lerged = '0'
hook_source = 'call coc#util#install()'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tpope/vim-endwise'
