[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'reireias/vim-cheatsheet'

[[plugins]]
repo = 'Shougo/denite.nvim'

