command_timeout = 2000

# k8s を最も右に表示する
format = "$all$kubernetes$line_break$character"

[directory]
style = "#FFEB3B"

[git_branch]
symbol = " "
style = "#FFEB3B"

[kubernetes]
format = 'on [⎈  $context \($namespace\)](dimmed green) '
disabled = false

[gcloud]
disabled = true
